### PR TITLE
Display scanlength on static qc pages for all scan types

### PR DESCRIPTION
**Pull request by josephmje**

### CODE REVIEW

**Comment by jerdra** [comment]
wouldn't changing from [3] to [-1] mean we obtain the primary slice direction axis for non-fmri scans? What do we mean from scanlength? Temporal or # of slices?

**Comment by josephmje** [comment]
For 4D scans, we'd get temporal. For everything else, we'd get the number of slices.

**Comment by jerdra** [comment]
Number of slices might still be relevant to capture for fmri

**Comment by jerdra** [comment]
also I'm not entirely sure that 3rd dimension is necessarily primary slice direction. If i'm right, Nifti convention is RAS, the S/I axis isn't always the slice encoding direction. Lmk if I'm just wrong about this

**Comment by jerdra** [comment]
Sorry for spam, but see: 

http://nipy.org/nibabel/reference/nibabel.nifti1.html 
Check get_dim_info(), that'll get you the slice direction!

**Comment by josephmje** [comment]
this would be running get_data_shape(), not get_dim_info()

**Pull request closed without merging**
