### PR TITLE
ENH: Add defacing script

### PR DESCRIPTION
**Pull request by josephmje**
Added a script to perform defacing.

I'm looking for some suggestions on better implementation with datman and the dashboard:
- Should `--suffix-id` come from the study config?
- I ended up saving the pydeface command to the json file. Not sure if we should overwrite the original scan. My initial preference is to keep both files. It could be good to use both to create a mask overlay QC image and then if we want, we can replace the original image after QC

### CODE REVIEW

**Review by DESm1th — DISMISSED** [review]
Looks good Mike! Thank you. Is there any possibility of the deface command failing silently though?

**Comment by jerdra** [comment]
> Looks good Mike! Thank you. Is there any possibility of the deface command failing silently though?

might make sense to call `pydeface.utils.deface_image` directly? Our inputs seem simple enough and we don't have to deal with weird cmdline arg construction or sub-process handling

**Comment by josephmje** [comment]
> might make sense to call `pydeface.utils.deface_image` directly? Our inputs seem simple enough and we don't have to deal with weird cmdline arg construction or sub-process handling

Thanks for the suggestion! Done in b0a76c6

**Review by jerdra — APPROVED** [review]

**Review by slimnsour — APPROVED** [review]
Looks good to me! Just tested it out and it works as expected too

**Pull request merged**
