### PR TITLE
Add qa-dti pipeline to datman, refactor dm_qc_report phantom section, generalize phantom pipelines for config

### PR DESCRIPTION
**Pull request by jerdra**
Reference to issue #1494, with some generalizations and refactoring. 

Newest qa-dti is integrated into dm_qc_report for SPINS study. 

In addition I've added a new tag key in tigrlab_config.yaml for selecting custom phantom pipelines. Using the option 'default' or a lack of 'qc_pha' key will use 'qc_type' instead.

### CODE REVIEW

**Comment by DESm1th** [comment]
Hey Jerry, thanks for this! I'll merge it in. Did you (or anyone) add the new keys to our archive copy of tigrlab_config.yaml? That might be the next step if not so we can start running your code.

**Comment by jerdra** [comment]
Haha I did it mostly for myself :), i'll take that as the go ahead and update the old tigrlab_config!

**Comment by jerdra** [comment]
tigrlab_config updated

**Comment by DESm1th** [comment]
Thanks Jerry!

**Pull request merged**
