### PR TITLE
[ENH] Allow the subid field to be modified between naming conventions

### PR DESCRIPTION
**Pull request by DESm1th**
To change the subject ID field of an ID add something formatted like the below example to the ID_MAP in a study's settings

```yml
ID_MAP:
    SUBJECT:
        'kcni_regex->replacement_str': 'dm_regex->replacement_str'
```

### CODE REVIEW

**Review by josephmje — APPROVED** [review]
This looks good to me @DESm1th! I can see the kcni_regex possibly being annoying to code but this will do. Have you come across any other studies other than PACTMD where we would need to remap the subject id? If so, we might want to include more tests for those patterns.

**Comment by DESm1th** [comment]
NEUR also needs it, not sure yet about other studies

**Comment by jerdra** [comment]
ooo yeah these seem a bit difficult to deal with :vomiting_face: special cases :vomiting_face:... is there an alternative way to store this as SUBJECT --> KCNI = <regex, replace> and SUBJECT --> DATMAN = <regex, replace> as list elements instead of encoding stuff directly into the <key> and <value>? 

This is defs nitpicking tbf

**Comment by DESm1th** [comment]
I thought about doing something like that but in a lot of places it would mean extra code to determine whether to grab the KCNI or datman entry, possibly in the calling script itself.

**Comment by jerdra** [comment]
always one step ahead of me :laughing:

**Review by jerdra — APPROVED** [review]

**Pull request merged**
